name: Build&Upload

on:
  workflow_dispatch:
  release:
    types:
      - released

env:
  Python_Version: 3.9

jobs:
  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{env.Python_Version}}
      - name: Build sdist
        run: |
          python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: dist/*.tar.gz
          retention-days: 1
          
  build_wheels:
    name: Build wheels on ${{ matrix.os }} ${{matrix.arch}}
    runs-on: ${{ matrix.os }}
    env:
      CIBW_DEPENDENCY_VERSIONS: latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, AMD64, aarch64, i686, arm64, universal2]
        exclude:
         - os: ubuntu-latest
           arch: AMD64
         - os: ubuntu-latest
           arch: i686
         - os: ubuntu-latest
           arch: arm64
         - os: ubuntu-latest
           arch: universal2
           
         - os: macos-latest
           arch: AMD64
         - os: macos-latest
           arch: i686
         - os: macos-latest
           arch: aarch64
         
         - os: windows-latest
           arch: x86_64
         - os: windows-latest
           arch: arm64
         - os: windows-latest
           arch: aarch64
         - os: windows-latest
           arch: i686
         - os: windows-latest
           arch: universal2
           
        include:
         - os: ubuntu-latest
           CIBW_PLATFORM: linux
           CIBW_BUILD: "cp3*-manylinux*"
           CIBW_BEFORE_ALL: "yum install -y centos-release-scl && yum install -y devtoolset-10"
           CIBW_BEFORE_BUILD: "source scl_source enable devtoolset-10 && pip install --upgrade cmake"
           CIBW_REPAIR_WHEEL_COMMAND: ""
           CIBW_ENVIRONMENT:
              CFLAGS="-flto -Ofast -pipe"
              CXXFLAGS="-flto -Ofast -pipe"
              
         - os: macos-latest
           CIBW_PLATFORM: macos
           CIBW_BUILD: "{cp,pp}3*-macosx*"
           CIBW_BEFORE_ALL: "brew install libomp"
           CIBW_BEFORE_BUILD: "pip install --upgrade cmake"
           CIBW_REPAIR_WHEEL_COMMAND: "delocate-listdeps --all --depending {wheel} && delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"
           CIBW_ENVIRONMENT:
              USE_OMP=True
              CPPFLAGS="$CPPFLAGS -flto -Xpreprocessor -fopenmp"
              CFLAGS="-flto -Ofast -pipe -I/usr/local/opt/libomp/include -lcblas -lclapack -framework Accelerate -framework OpenCL"
              CXXFLAGS="-flto -Ofast -pipe -I/usr/local/opt/libomp/include -lcblas -lclapack -framework Accelerate -framework OpenCL"
              LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"
              
         - os: windows-latest
           CIBW_PLATFORM: windows
           CIBW_BUILD: "{cp,pp}3*-win_amd64*"
           CIBW_BEFORE_ALL: ""
           CIBW_BEFORE_BUILD: "pip install --upgrade cmake && pip install delvewheel"
           CIBW_REPAIR_WHEEL_COMMAND: "delvewheel repair -w {dest_dir} {wheel}"
           CIBW_ENVIRONMENT:
              CFLAGS="-flto -Ofast -pipe"
              CXXFLAGS="-flto -Ofast -pipe"
           
      fail-fast: false 
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{env.Python_Version}}
      - name: Set up QEMU
        if: ${{ matrix.CIBW_PLATFORM == 'linux' && matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Build wheels on ${{ matrix.CIBW_PLATFORM }} ${{matrix.arch}}
        uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_PLATFORM:  ${{ matrix.CIBW_PLATFORM }}
          CIBW_BUILD: ${{matrix.CIBW_BUILD}}
          CIBW_SKIP: "cp35-*"
          CIBW_ENVIRONMENT: ${{matrix.CIBW_ENVIRONMENT}}
          CIBW_ARCHS: ${{matrix.arch}}
          CIBW_DEPENDENCY_VERSIONS: ${{ env.CIBW_DEPENDENCY_VERSIONS }}
          CIBW_BEFORE_BUILD: ${{matrix.CIBW_BEFORE_BUILD}}        
          CIBW_BEFORE_ALL: ${{matrix.CIBW_BEFORE_ALL}}
          CIBW_REPAIR_WHEEL_COMMAND: ${{matrix.CIBW_REPAIR_WHEEL_COMMAND}}
          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64:latest
          CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux2014_aarch64:latest

      - uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: ./wheelhouse/*.whl
          retention-days: 1

          
  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'release' || github.event_name == 'workflow_dispatch'}}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bdist_wheel
          path: ./dist
      - uses: actions/download-artifact@v2
        with:
          name: sdist
          path: ./dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_PASSWORD }}
          repository_url: ${{ secrets.JFROG_URL }}
          packages_dir: ./dist
          verify_metadata: true
          skip_existing: false
          verbose: true
