name: Build&Upload

on:
  workflow_dispatch:
  release:
    types:
      - released

env:
  Python_Version: 3.9

jobs:
  build_sdist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{env.Python_Version}}
      - name: Build sdist
        run: |
          pip install setuptools-git-versioning
          python setup.py sdist
      - uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: dist/*.tar.gz
          retention-days: 1
          
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: true

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{env.Python_Version}}
      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64
      - name: Build wheels
        uses: pypa/cibuildwheel@v1.12.0
        env:
          CIBW_PLATFORM: auto 
          CIBW_BUILD: "cp3*-*"
          CIBW_SKIP: "cp35-* cp36-* *-win32 pp*"
          CIBW_PROJECT_REQUIRES_PYTHON: ">=3.7.8"
          CIBW_ENVIRONMENT: "CFLAGS='-Ofast -pipe -flto' CXXFLAGS='-Ofast -pipe -flto' BUILD_TIME=$(date)"
          CIBW_ARCHS_LINUX: "x86_64 aarch64"
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_ARCHS_WINDOWS: "AMD64"
          CIBW_MANYLINUX_X86_64_IMAGE: quay.io/pypa/manylinux2014_x86_64:latest
          CIBW_MANYLINUX_AARCH64_IMAGE: quay.io/pypa/manylinux2014_aarch64:latest
          CIBW_DEPENDENCY_VERSIONS: latest
          CIBW_BEFORE_BUILD: "pip install --upgrade cmake"
          
          CIBW_BEFORE_ALL_LINUX: yum install -y centos-release-scl && yum install -y devtoolset-10 && yum update -y glibc-devel
          CIBW_BEFORE_BUILD_LINUX: source scl_source enable devtoolset-10
          
          CIBW_BEFORE_BUILD_WINDOWS: "pip install delvewheel"
          CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair -w {dest_dir} {wheel}"
          
          CIBW_ENVIRONMENT_MACOS: 
            USE_OMP=True
            CPPFLAGS="$CPPFLAGS -Xpreprocessor -fopenmp"
            CFLAGS="$CFLAGS -I/usr/local/opt/libomp/include"
            CXXFLAGS="$CXXFLAGS -I/usr/local/opt/libomp/include"
            LDFLAGS="$LDFLAGS -Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"
          CIBW_BEFORE_ALL_MACOS:
            brew install libomp
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "delocate-listdeps --all --depending {wheel} && delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -v {wheel}"

      - uses: actions/upload-artifact@v2
        with:
          name: bdist_wheel
          path: ./wheelhouse/*.whl
          retention-days: 1
          
  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'release' || github.event_name == 'workflow_dispatch'}}
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: bdist_wheel
          path: ./dist
      - uses: actions/download-artifact@v2
        with:
          name: sdist
          path: ./dist
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.JFROG_USER }}
          password: ${{ secrets.JFROG_PASSWORD }}
          repository_url: ${{ secrets.JFROG_URL }}
          packages_dir: ./dist
          verify_metadata: true
          skip_existing: false
          verbose: true
